[package]
name = "vmprotect-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0.50", features = ["full"] }
twox-hash = "1.6"
hex = "0.4.2"
proc-macro2 = "1.0.78"

vmprotect-sys = { path = "../vmprotect-sys" }
